sudo: false

language: node_js

node_js:
  - '6'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - yarn lint
  - yarn test:cover

after_success:
  - yarn codeclimate
  - yarn coveralls

addons:
  code_climate:
    repo_token: aa4ce74e49bf981e70c0ba0e362815e519bcd2f2fa617fd972cf96b3433c974c

cache:
  directories:
    - node_modules
  yarn: true
